version: '3.8'

services:
  nutrition_tracker:
    build: .
    container_name: nutrition_tracker_app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=${FLASK_ENV:-development}
      - USE_MYSQL=true
      - DB_HOST=192.168.11.1
      - DB_PORT=3306
      - DB_USER=remote_user
      - DB_PASS=BuGr@d@N4@loB6!
      - DB_NAME_DEV=nutri_tracker_dev
      - DB_NAME_PROD=nutri_tracker_prod
      # For Docker network bridge - this allows the container to reach the host MySQL
      - DOCKER_DB_HOST=host.docker.internal
    volumes:
      - ./database.db:/app/database.db  # Mount local SQLite for migration
      - ./logs:/app/logs
    # Network configuration options:

    # Option 1: Use extra_hosts (recommended for most cases)
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "mysql-host:192.168.11.1"

    # Option 2: Use host network mode (uncomment if Option 1 doesn't work)
    # network_mode: "host"

    # Option 3: Custom bridge network (see networks section below)
    networks:
      - nutrition_network

    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

# Custom network configuration
networks:
  nutrition_network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: nutrition_br
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1

# Volume for persistent data (if needed)
volumes:
  nutrition_data:
    driver: local
