version: '3.8'

services:
  nutrition-tracker:
    build: .
    container_name: nutrition_tracker_app
    ports:
      - "8080:8080"
    environment:
      - USE_MYSQL=true
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USERNAME=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=false
    volumes:
      - ./logs:/app/logs
    # Network configuration options:

    # Option 1: Use extra_hosts (recommended for most cases)
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "mysql-host:192.168.11.1"

    # Option 2: Use host network mode (uncomment if Option 1 doesn't work)
    # network_mode: "host"

    # Option 3: Custom bridge network (see networks section below)
    networks:
      - nutrition_network

    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

# Custom network configuration
networks:
  nutrition_network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: nutrition_br
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1

# Volume for persistent data (if needed)
volumes:
  nutrition_data:
    driver: local
